// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// Donsker_correl_cpp
double Donsker_correl_cpp(double u, double v, NumericVector sorted_obs_data);
RcppExport SEXP _admix_Donsker_correl_cpp(SEXP uSEXP, SEXP vSEXP, SEXP sorted_obs_dataSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type u(uSEXP);
    Rcpp::traits::input_parameter< double >::type v(vSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type sorted_obs_data(sorted_obs_dataSEXP);
    rcpp_result_gen = Rcpp::wrap(Donsker_correl_cpp(u, v, sorted_obs_data));
    return rcpp_result_gen;
END_RCPP
}
// estimVarCov_empProcess_Rcpp
NumericMatrix estimVarCov_empProcess_Rcpp(NumericVector t, NumericVector obs_data);
RcppExport SEXP _admix_estimVarCov_empProcess_Rcpp(SEXP tSEXP, SEXP obs_dataSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type t(tSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type obs_data(obs_dataSEXP);
    rcpp_result_gen = Rcpp::wrap(estimVarCov_empProcess_Rcpp(t, obs_data));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_admix_Donsker_correl_cpp", (DL_FUNC) &_admix_Donsker_correl_cpp, 3},
    {"_admix_estimVarCov_empProcess_Rcpp", (DL_FUNC) &_admix_estimVarCov_empProcess_Rcpp, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_admix(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
